### ISSUE TITLE
DNS record create-or-update fatal, works with create

### ISSUE THREAD

**Issue by uded** [cloudflare/cloudflare-go#1015]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.46.0

### Go environment

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOVCS=
set GOVERSION=go1.18.4
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C....

### Expected output

A summary of created or update record

### Actual output

```panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xcb2854]

goroutine 1 [running]:
main.dnsCreateOrUpdate(0xc000125d40?)
        /home/runner/work/cloudflare-go/cloudflare-go/cmd/flarectl/dns.go:137 +0x654
github.com/urfave/cli/v2.(*Command).Run(0xc000125d40, 0xc00002ab40)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.11.1/command.go:169 +0x631
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc0001101c0, 0xc00002a940)
github.com/urfave/cli/v2.(*Command).startApp(0xc0001258c0, 0xc00002a940)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.11.1/command.go:287 +0x79b
github.com/urfave/cli/v2.(*Command).Run(0xceebe0?, 0xc000056fb0?)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.11.1/command.go:95 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc000110000, {0xe04a08?, 0xc000012060}, {0xc00011a000, 0xd, 0x10})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.11.1/app.go:378 +0xf15
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.11.1/app.go:251
main.main()
        /home/runner/work/cloudflare-go/cloudflare-go/cmd/flarectl/flarectl.go:715 +0x526d```

### Code demonstrating the issue

N/A

### Steps to reproduce

1. `flarectl.exe d o --zone domain --content="mx.domain.com" --type MX --ttl 3600 --priority 1 --name="domain"` doesn't work
2. Changing `d o` to `d c` works fine

### References

None as far as I was checking

**Comment by jacobbednarz** [comment]
~have you tried `--zone` with a zone ID, not a zone name?~ disregard, this does a lookup for you internally.

**Comment by uded** [comment]
Tried many options. Gave me the same fatal panic error

**Comment by Cyb3r-Jak3** [comment]
@uded What happens if you do `flarectl.exe d u --zone domain --content="mx.domain.com" --type MX --ttl 3600 --priority 1 --name="domain"`. I can't recreate on Windows or Linux, and I'm wondering if there is something wrong with updating DNS records or if to do with create and update specifically. For your MX record domain or content, is there anything that might be considered non-standard? Like it being an [Internationalized Domain Names (IDNs)](https://developers.cloudflare.com/email-routing/known-limitations/)?
