### ISSUE TITLE
flarectl can create SRV records ?

### ISSUE THREAD

**Issue by laymonk** [cloudflare/cloudflare-go#243]
Hi,

cannot tell why the following command is failing.  

```
flarectl dns create-or-update --zone example.com \
  --type SRV \
  --name _caldavs._tcp.example.com \
  --content 'SRV 0 1 443 mail.example.com.' \
  --proxy false --ttl 120 --priority 1 \
  --data  '{"service":"_caldavs","proto":"_tcp","name":"example.com","priority":0,"weight":1,"port":443,"target":"mail.example.com"}'
```

* I get errors like the following, but notice that I have specified 'service' within data.
```
Error creating DNS record: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"DNS Validation Error\",\"error_chain\":[{\"code\":9101,\"message\":\"service is a required data field.\"}]}],\"messages\":[],\"result\":null}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x456dba]

goroutine 1 [running]:
main.dnsCreateOrUpdate(0xc420010f00)
        /home/travis/gopath/src/github.com/cloudflare/cloudflare-go/cmd/flarectl/dns.go:132 +0x76f
github.com/cloudflare/cloudflare-go/cmd/flarectl/vendor/github.com/codegangsta/cli.Command.Run(0x7b5f93, 0x10, 0x0, 0x0, 0xc420048da0, 0x1, 0x1, 0x7c0893, 0x2b, 0x0, ...)
        /home/travis/gopath/src/github.com/cloudflare/cloudflare-go/cmd/flarectl/vendor/github.com/codegangsta/cli/command.go:174 +0x93c
github.com/cloudflare/cloudflare-go/cmd/flarectl/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc420010c80, 0xc420010b40, 0x0, 0x0)
        /home/travis/gopath/src/github.com/cloudflare/cloudflare-go/cmd/flarectl/vendor/github.com/codegangsta/cli/app.go:298 +0x8fa
github.com/cloudflare/cloudflare-go/cmd/flarectl/vendor/github.com/codegangsta/cli.Command.startApp(0x7b27a0, 0x3, 0x0, 0x0, 0xc420048d60, 0x1, 0x1, 0x7b458c, 0xb, 0x0, ...)
        /home/travis/gopath/src/github.com/cloudflare/cloudflare-go/cmd/flarectl/vendor/github.com/codegangsta/cli/command.go:249 +0x55c
github.com/cloudflare/cloudflare-go/cmd/flarectl/vendor/github.com/codegangsta/cli.Command.Run(0x7b27a0, 0x3, 0x0, 0x0, 0xc420048d60, 0x1, 0x1, 0x7b458c, 0xb, 0x0, ...)
        /home/travis/gopath/src/github.com/cloudflare/cloudflare-go/cmd/flarectl/vendor/github.com/codegangsta/cli/command.go:65 +0x1304
github.com/cloudflare/cloudflare-go/cmd/flarectl/vendor/github.com/codegangsta/cli.(*App).Run(0xc420010a00, 0xc420010140, 0x13, 0x14, 0x0, 0x0)
        /home/travis/gopath/src/github.com/cloudflare/cloudflare-go/cmd/flarectl/vendor/github.com/codegangsta/cli/app.go:187 +0x8f9
main.main()
        /home/travis/gopath/src/github.com/cloudflare/cloudflare-go/cmd/flarectl/flarectl.go:643 +0x4b5e
```
* Is it possible I have entirely gotten wrong how the data parameter is formatted ?

**Comment by jacobbednarz** [comment]
Thanks for the report @laymonk! Just looking at the code and documentation for this, `--data` isn't a supported flag (see https://github.com/cloudflare/cloudflare-go/blob/aa07f8c57bcb06db0b1d4dfe7b685140826822c6/cmd/flarectl/flarectl.go#L314-L346). This leads me to believe SRV records aren't supported within `flarectl` as the API expects `data` to be a part of the payload.

Happy to review a PR for this functionality if you'd like to take a crack at it!

**Comment by pmocek** [comment]
Does flarectrl intend to warn or fail with error upon finding unrecognized command line arguments, or to silently ignore them?  If the former, this looks like a bug.
